### ISSUE TITLE
Stop using Mix.env

### ISSUE THREAD

**Issue by noma4i** [radar/elastic#13]
Make sure these boxes are checked before submitting the issue:

- [x] I have provided steps to reproduce the issue.
**I want to use elastic in my release.**
- [x] I have explained clearly what is happening, and what I expect to happen.
**I expect that release will work, and it doesn't** 

Elixir app release is compiled w/o Mix while it's not clear during compiling process it will lead to a app crash right after Mix.* will be evaluated.

Culprit: https://github.com/radar/elastic/blob/master/lib/elastic/index.ex#L81

Steps to reproduce: use exrm/distillery to build release, start. Execute code related to elastic lookup, get erl_crash.dump

**Comment by radar** [comment]
Please provide steps to reproduce this issue.

**Comment by radar** [comment]
And by steps I mean an exact walkthrough. Your steps that have been provided so far are extremely vague.

**Comment by noma4i** [comment]
This issue is about using Elastic package in compiled release. Problem comes from the nature of beam application which doesn't have Mix.* module included by default and is not welcome to be included in compiled release.   

Exrm discussion about Mix in release
https://github.com/bitwalker/exrm/issues/67#issuecomment-60040251

Example issue with same problem 
https://github.com/honeybadger-io/honeybadger-elixir/issues/8

Rabbitmq - same issue
https://github.com/rabbitmq/rabbitmq-cli/issues/174

**Comment by radar** [comment]
Please submit a patch to fix this issue.

**Comment by noma4i** [comment]
Verbal fix: don't code like that in the future.
Pull request will be done later.
