### ISSUE TITLE
Wrong markdown indentation in documentation

### ISSUE THREAD

**Issue by miskolc** [radar/elastic#5]
The code examples at:
https://hexdocs.pm/elastic/Elastic.Document.API.html
for `Answer.raw_search`, `Answer.get` and so on need extra indentation to be displayed as code.

**Comment by radar** [comment]
Looks like it was just missing some triple-backticks: 4e91130. Or am I missing something else?

**Comment by radar** [comment]
Published 2.3.3 with this documentation fix. Thanks for pointing that out!
